# Generated by Django 5.0.7 on 2025-05-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ic_number', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
