# Generated by Django 5.0.7 on 2025-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0003_remove_donor_email_remove_donor_password_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
