# Generated by Django 5.0.7 on 2025-06-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0004_donor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='ic_number',
            new_name='donorIC',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='full_name',
            new_name='donorName',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='email',
            new_name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.AddField(
            model_name='donor',
            name='contactNumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='donorID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
