# Generated by Django 5.0.7 on 2025-06-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0006_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date',
            new_name='donation_date',
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(max_length=50),
        ),
    ]
