# Generated by Django 5.0.7 on 2025-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0007_rename_date_donation_donation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('Credit/Debit Card', 'Credit/Debit Card'), ('Online Banking', 'Online Banking'), ('QR Code', 'QR Code')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='qr_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('General', 'General'), ('Mosque Maintenance', 'Mosque Maintenance'), ('Charity', 'Charity')], max_length=50),
        ),
    ]
