# Generated by Django 5.0.7 on 2025-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0008_rename_donation_date_donation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
