# Generated by Django 5.0.7 on 2025-06-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0010_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
