# Generated by Django 5.0.7 on 2025-06-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0012_donationcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasurerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='donationcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('Chairman', 'Chairman'), ('Treasurer', 'Treasurer')], max_length=20),
        ),
    ]
