# Generated by Django 5.0.7 on 2025-06-18 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0013_treasureraction_donationcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hompage.donationcategory'),
        ),
    ]
