# Generated by Django 5.0.7 on 2025-06-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0016_treasureraction_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcategoryrequest',
            name='treasurer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hompage.adminprofile'),
            preserve_default=False,
        ),
    ]
