# Generated by Django 5.0.7 on 2025-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0017_donationcategoryrequest_treasurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcategoryrequest',
            name='data_after',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcategoryrequest',
            name='data_before',
            field=models.TextField(blank=True, null=True),
        ),
    ]
