# Generated by Django 5.0.7 on 2025-06-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0021_alter_donor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
    ]
