# Generated by Django 5.0.7 on 2025-06-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hompage', '0024_alter_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
